### ISSUE TITLE
General question

### ISSUE THREAD

**Issue by blocka** [nueverest/blowdrycss#3]
As a developer, I love the ideas presented here (well presented other places, but implemented here), as developers (at least good ones) love abstractions, and love keeping things DRY.

However, I'm stuck working with css/html guys that are stuck in bem land, even after we've moved to a component based architecture (vue 2.0). I asked them what they think of this, and the two major issues they had where:
1. Hard to "maintain". Meaning that if you wanted to globally change the padding of all inputs, it would be a pain to manually go and change the class on all of them. My working assumption is that the atomic css pattern is actually meant for components, and not for global css theming, which this doesn't mess with.
2. An eye sore. The proliferation of classes makes the html easier to read. This is probably just an aesthetic issue, but I was wondering if you had any thoughts on that.

**Comment by nueverest** [comment]
Thanks for the feedback.

I've been using blowdrycss along with Zurb Foundation in a production environment for the past 6 months.

**Maintenance**
I've found that the blowdrycss portion does not require any maintenance. I someone says I want the title blue I add `blue` and I'm done.  I do have some general theming setup inside of SCSS libraries and Foundation.  Those require maintenance, extra meetings, and slower development.  It also requires each new person to learn a unique theme syntax that will evolve over time.  The thing that helps reduce the maintenance headache is the style guide.  Once the team agreed, I built an admin page that shows the currently agreed upon standard.   

**Eye Sore**
When first exposed to a long string of atomic classes it might be intimidating.  However, by just reading it like a sentence there is no difficulty.  I also found that adding text styles on the left and box styles on the right helps the reader. 

`class="text-align-center font-size-12 bold padding-5 margin-top-10-medium-down margin-right-50"`

**Downsides to the BEM Approach**
-  Slow: A big downside to the BEM approach is that it slows down the styling process at each step along the way.  On the atomic side I already know CSS so with blowdrycss I'm 90% there.  Here are some of the ways BEM slows down development.

BEM causes context switching back and forth between CSS, HTML, JS, Server Code, and maybe even the DB if it has CSS in it.  The need for the context switch is clear either a class needs to be found or written. With the BEM approach the CSS is not going to write itself.  In contrast, blowdrycss's atomic model reduces human error and context switching thus speeding up development. 

Refactoring is also slow and error prone for BEM. Consider this BEM:

``` css
.block { You actually have to write stuff in here. }
.block__element { You have to know what is defined in the block to prevent duplication. }
.block--modifier { You have to write stuff here too. }
```

Let's say I feel the name `.block` needs to change to `shinyblock`. I will now need to refactor every element and modifier that starts with `block` in the CSS, HTML, JS, Backend Server Code, and in CSS that comes from the Database.  That makes me not want to refactor, and I just wasted time coming to that conclusion. 
- BEM is brittle when it comes to split testing, page overhauling, and design changes.  For split testing sometimes I see people doing things like creating `.landingpage1` and `.landingpage2`.  With atomic CSS I never need to think about a model. The model is CSS itself.  When a designer comes to me with a radically different design I do not think twice with atomic CSS, but with BEM I start hearing myself complain because now I have to write or re-write lots of new CSS.
- BEM is very implicit. Consider the following from [this site](http://csswizardry.com/2013/01/mindbemding-getting-your-head-round-bem-syntax/).

``` html
<div class="media">
    <img src="logo.png" alt="Foo Corp logo" class="media__img--rev">
    <div class="media__body">
        <h3 class="alpha">Welcome to Foo Corp</h3>
        <p class="lede">Foo Corp is the best, seriously!</p>
    </div>
</div>
```

There are lots of classes here: `media, media__image--rev, media__body, alpha, lede`. 

It is 100% implicit. What do the classes do? Where are they defined? Why does the word 'media' not appear in front of `alpha and lede`? Why is the word 'media' used? Is it because image media is inside the div? Is it because this is the media page that we send to the newspaper? The answer to all of these questions is I will have to discover where the css is that defines each of these classes, or open up the browser inspector.  

On the other hand, if I rewrite the html above with atomic class selectors I have the following:

``` html
<div class="max-width-1000 text-align-center padding-top-20-large-up">
    <img src="logo.png" alt="Foo Corp logo" class="width-50 height-50">
    <div class="font-size-16 font-weight-400 padding-20 border-black-solid-1px margin-top-30">
        <h3 class="green">Welcome to Foo Corp</h3>
        <p class="text-align-left pink">Foo Corp is the best, seriously!</p>
    </div>
</div>
```

This is very explicit, and does not require deep inquiry.  Yes, it does make the HTML more verbose, but it makes the CSS much less so. The other thing is that is still requires knowledge of CSS property names and values.  So all of the time spent learning CSS still pays off.
